linters:
  run:
    concurrency: 2
    skip-dirs:
      - tests/composefiles
  enable-all: false
  disable-all: true
  enable:
    - deadcode
    - errcheck
    - gocyclo
    - gofmt
    - goimports
    - golint
    - gosimple
    - govet
    - ineffassign
    - interfacer
    - lll
    - misspell
    - nakedret
    - staticcheck
    - structcheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - varcheck
linters-settings:
  gocyclo:
    min-complexity: 21
  lll:
    line-length: 200
